test-all:
  cargo test --

test example:
  cargo test --test {{example}} -- --nocapture

doc:
  cargo doc --no-deps --workspace

clippy:
  cargo clippy

fmt:
  cargo fmt --all

all:
  just fmt
  just clippy
  just doc
  just test-all
