test-all:
  cargo test -- --nocapture

test example:
  cargo test --test {{example}} -- --nocapture

doc:
  cargo doc

clippy:
  cargo clippy

fmt:
  cargo fmt --all

all:
  just fmt
  just clippy
  just doc
  just test-all
