max_width = 120
fn_call_width = 100
attr_fn_like_width = 100
struct_lit_width = 20
struct_variant_width = 40
array_width = 60
chain_width = 60
single_line_if_else_max_width = 60
reorder_impl_items = true
group_imports = "StdExternalCrate"
wrap_comments = true
format_code_in_doc_comments = true
format_strings = true